import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import StoreProvider from "./storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<StoreProvider>
					<div className='grid h-screen grid-rows-[auto_1fr] gap-24'>
						<Header />

						<main className='mx-w-3xl '>{children}</main>
					</div>
				</StoreProvider>
				{/* <Header />
				{children} */}
			</body>
		</html>
	);
}
